// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1:string):Promise<void>;

export function GetGicon():Promise<string>;

export function ShutDown():Promise<void>;

export function TranscodeAVIToMp4(arg1:string):Promise<string>;
