// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1) {
  return window['go']['transcode']['Services']['Debug'](arg1);
}

export function GetGicon() {
  return window['go']['transcode']['Services']['GetGicon']();
}

export function ShutDown() {
  return window['go']['transcode']['Services']['ShutDown']();
}

export function TranscodeAVIToMp4(arg1) {
  return window['go']['transcode']['Services']['TranscodeAVIToMp4'](arg1);
}
